### ISSUE TITLE
功能需求 - 新增媒体库路径时提供二级分类选项

### ISSUE THREAD

**Issue by ArthurSmoke** [NAStool/nas-tools#4273]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: v3.1.4 9e4252e
> 环境: docker 

## 你想要新增或者改进什么功能？
> 在媒体库中设置目录时，可以根据基础设置-二级分类设置中的配置，提供不同分类的目的目录

## 这个功能有什么可以参考的资料吗？
> 目前的二级分类功能，已经可以解决国产剧，日剧等不同剧集的下载目录和存储目录的区分，但是相对于电影资源来说，电视剧资源占用空间更大，常常分在不同的磁盘保存，希望能根据二级分类功能，使下载完成后转移到对应的目录保存

### 二级分类配置
```yaml
tv:
  CN:
    origin_country: 'CN,TW,HK'
  US:
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  JP:
    origin_country: 'JP'
  KR:
    origin_country: 'KP'
  Show:
    genre_ids: '10764'
```
### 目录树
mnt/video1/TVseries
  |--CN
  |--JP

mnt/video2/TVseries
  |--US
  |--KR
  |--SHow

### 预期功能
新增媒体库路径时提供二级分类选项
![screenshot-20230413-001028](https://user-images.githubusercontent.com/1540343/231518168-c66c0658-7a06-4ba2-b826-e66a1cbac890.png)
![screenshot-20230413-000143 (1)](https://user-images.githubusercontent.com/1540343/231518201-32e1801b-1a6e-4802-a601-128bd06b64d8.png)
下载完成后转移时按照二级分类对应的目录转移
