### ISSUE TITLE
双栈网络环境下，IPV4网络无法接收到TG的推送信息

### ISSUE THREAD

**Issue by mildnes** [NAStool/nas-tools#4635]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.2.1 f4efbf2
> 环境: docker or windows or Synology
>本地环境，路由配置了出国，本地unraid安装的docker。unraid上面安装了Nginx Proxy Manager反代NT（有泛域名证书）
基础配置里面填写了https://IP:8443的地址。路由里面端口映射已经配置了8443对外，运营商也没有封掉端口号。

## 你遇到什么问题了？
在双栈环境中，emby发送webhook推送到NT，IPV4的地址无法收到微信和tg的消息，IPV6可以收到。查看了日志。
```
2023-05-04 17:18:36,211 INFO: 处理事件：emby.webhook - [<function MediaSyncDel.sync_del at 0x15267ee6a710>, <function MovieLike.favtransfer at 0x15267ee6ab90>, <function SpeedLimiter.emby_action at 0x15267ee6beb0>, <function Webhook.send at 0x15267ee8dcf0>]
2023-05-04 17:18:36,318 INFO: 【Message】发送消息 微信：title=停止播放剧集 财阀家的小儿子 S1E2 你能看到未来？, text=用户：mildnes
设备：Emby Web Chrome Windows
位置：fd17::1 
进度：0.78%
剧情：炫优意识到自己重生为顺洋家族的小孙子陈导俊。导俊向祖父陈养喆会长提出了有利的建议。他很快便赢得养喆的信任，成为养喆最宠爱的孙子…
时间：2023-05-04 17:18:36
```
这个就是IPV6会推送，IPV4地址则不会。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
配置文件如下
```
# 【配置注意要符合yaml语法，:号后有1个空格，不能使用全角标点符号】
# 【最新版本已经可以通过WEB页面对所有配置项进行配置，推荐使用WEB页面进行配置】
app:
  # 【日志记录类型】：server、file
  # 如果是使用Docker安装建议设置为file，将日志输出到配置文件目录
  # 如果是使用群晖套件建议配置为 server，可将日志输出到群晖的日志中心便于查看
  logtype: file
  # 【日志文件的路径】：logtype为file时生效
  logpath: /config/logs
  # 【群晖日志中心IP和端口】：logtype为SERVER时生效。端口一般是514，只需要改动IP为群晖的IP，示例：127.0.0.1:514
  logserver: 127.0.0.1:514
  # 【日志级别】：info、debug、error
  loglevel: debug
  # 【WEB管理界面端口】：默认3000
  web_port: '3000'
  # 【WEB管理页面登录用户】，默认admin
  login_user: admin
  # 【WEB管理页面登录密码】：默认password，如果是全数字密码，要用''括起来
  login_password: '[hash]pbkdf2:sha256:260000$xVQg0DR9LwgXG2Hf$584dd0f15c58e056c41b27a1a15d049670d66bcce48d620965f3393c6e351c87'
  # 【WEB管理界面使用的HTTPS的证书和KEY的路径】，留空则不启用HTTPS
  ssl_cert: ''
  ssl_key: ''
  # 【TMDB API KEY】：需要在https://www.themoviedb.org/申请，必须配置，否则无法识别媒体资源和重命名
  # 以下地址需要网络能够正常访问：api.themoviedb.org、webservice.fanart.tv
  rmt_tmdbkey: 4f****
  # 【TMDB匹配模式】：normal、strict，normal模式下如使用文件名/种子名中的年份无法匹配到媒体信息，会去掉年份再匹配一次；strict模式则严格按文件中年份匹配
  # normal模式下会提升识别成功率，但也可能会导致误识别率增加；strict模式可以降低误识别率，但可能导致很多文件名/种子名中年份不正确的无法被识别（特别是剧集，需要是首播年份）
  rmt_match_mode: normal
  # 【设置代理】，themoviedb、fanart、telegram等将使用代理访问，http和https均需配置，可以是http也可以是socks5，但需要带http或socks5前缀，两项可以配置为一样，留空则不启用
  # 示例：'http://127.0.0.1:7890' 'socks5://127.0.0.1:8018'
  proxies:
    https:
    http:
  domain: https://nt.*****.xyz:8443
  # 【UserAgent】：可适当修改，用于PT站签到、豆瓣数据抓取等
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68

# 【配置媒体库信息】
  init_files:
  - init_filter.sql
  - init_rssparser.sql
  - init_siteuses.sql
  - init_userrss.sql
  - init_userrss_v2.sql
  - update_subscribe.sql
  - init_userrss_v3.sql
  - reset_db_version.sql
  - update_userrss.sql
  - update_userpris.sql
  - stop_all_service.sql
  - update_downloadsetting.sql
  - update_downloader.sql
  - update_systemdict.sql
  tmdb_domain: api.themoviedb.org
  wallpaper: themoviedb
  releases_update_only: false
  tmdb_image_url: ''
media:
  # 【媒体库管理软件】：emby、jellyfin、plex，需要在emby或jellyfin或plex区配置详细信息，用于下载检查控重、媒体库展示等，建议配置
  media_server: emby
  # 【媒体库电影文件存放目录】：支持配置多个目录，不同的硬盘需映射为不同的根目录，以更于程序区分
  movie_path:
  - /media/play/电影/
  tv_path:
  - /media/play/电视剧/
  anime_path:
  - /media/play/动漫/
  unknown_path:
  - /media/play/其他
  category: default-category
  # 【转移到媒体库的最小文件大小】：避免预告片/MV等影响识别，单位M
  min_filesize: '100'
  # 【洗版开关】：如开启则则新下载了更大的文件会覆盖媒体库目录中已有的文件
  filesize_cover: true
  # 【电影命名定义】：程序会按定义的命名格式对电影进行重命名；/代表上下级目录，{}内为占位符；占位符会使用文件识别出来的实际值替换；占位符外的字符会当成普通字符，直接体现在名称上
  # 电影占位符有：{title}：标题，{en_title}：英文标题，{original_title}：原语种标题，{original_name}：原文件名，{year}：年份，{edition}：版本(Bluray/WEB-DL等)，{videoFormat}：分辨率(1080p/4k等)，{videoCodec}：视频编码，{audioCodec}：音频编码及声道，{tmdbid}：TMDB的ID，{part}：part1/disc1/dvd1等
  movie_name_format: '{title} ({year})/{title}-{part} ({year}) - {videoFormat}'
  # 【电视剧命名定义】：程序会按定义的命名格式对电视剧进行重命名；/代表上下级目录，{}内为占位符；占位符会使用文件识别出来的实际值替换，占位符外的字符会当成普通字符，直接体现在名称上
  # 电视剧占位符有：{title}：标题，{en_title}：英文标题，{original_title}：原语种标题，{original_name}：原文件名，{year}：年份，{edition}：版本(Bluray/WEB-DL等)，{videoFormat}：分辨率(1080p/4k等)，{videoCodec}：视频编码，{audioCodec}：音频编码及声道，{tmdbid}：TMDB的ID，{season}：季数，{episode}：集数，{season_episode}：剧集SxxExx，{part}：part1/disc1/dvd1等
  tv_name_format: '{title} ({year})/Season {season}/{title}-{part} - {season_episode}
    - 第{episode}集'
  # 【生成NFO描述文件及海报】：开启后文件转移完成时会自动生成nfo描述文件及poster海报，协助媒体服务器识别和搜刮
  nfo_poster: true
  # 【实时刷新媒体库】：开启后文件转移完成时会实时刷新媒体服务器（Emby/Jellyfin/Plex）的媒体库
  refresh_mediaserver: true

# 配置Emby服务器信息
  mediasync_interval: '12'
  ignored_paths: ''
  ignored_files: ''
  media_default_path: /media
  default_rmt_mode: link
  tmdb_language: zh
emby:
  # 【Emby服务器IP地址和端口】：注意区分http和https，http时可以不加http://，https时必须加https://
  host: http://172.17.0.1:8096
  # 【Emby ApiKey】：在Emby设置->高级->API密钥处生成，注意不要复制到了应用名称
  api_key: db0cdfb001124a5ab5d1da47377c03a3

# 配置Jellyfin服务器信息
  play_host: 
jellyfin:
  # 【Jellyfin服务器IP地址和端口】：注意区分http和https，http时可以不加http://，https时必须加https://
  host: http://127.0.0.1:8096
  # 【Jellyfin ApiKey】：在Jellyfin设置->高级->API密钥处生成
  api_key:

# 配置Plex服务器信息
plex:
  # 【Plex服务器IP地址和端口】：注意区分http和https，http时可以不加http://，https时必须加https://
  host: http://127.0.0.1:32400
  # 【Plex服务器的名称】
  servername:
  # 【Plex用户名】
  username:
  # 【Plex用户密码】
  password:

# 【配置消息通知服务】
message:
  # 【发送消息使用的渠道】：wechat、serverchan、telegram、bark，需在对应的配置区域配置。不使用的渠道配置可以留空或者删除。推荐使用wechat微信渠道。不设置则不启用消息服务
  webhook_ignore:
  switch:
    download_start: true
    download_fail: true
    transfer_finished: true
    transfer_fail: true
    rss_added: true
    rss_finished: true
    site_signin: true
sync:
  # 【监控目录列表】：监控目录有文件变化时会自动进行媒体整理、转移并命名
  # 可以配置多个，使用|分隔，按'源目录|目的目录|未识别目录'格式配置，源目录为需要同步的目录，目的目录为识别和改名后存放的目录，未识别目录为无法识别时转移的目录
  # 配置格式1：'源目录'，比如：'/mnt/pt'，源目录文件会自动识别是电影、电视剧或动漫并分别转移到media中配置的movie_path、tv_path、anime_path目录中，未识别的会转移到media中配置的unknown_path中
  # 配置格式2：'源目录|目的目录'，比如：'/mnt/pt_movie|mnt/emby_movie'，源目录中文件不会区分类型，均往目的目录转移，未识别的会转移到media中配置的unknown_path中
  # 配置格式3：'源目录|目的目录|未识别目录'，比如：'/mnt/pt_movie|mnt/emby_movie|emby_unknown'，源目录中文件不会区分类型，均往目的目录转移，未识别的会转移到未识别目录中
  # 配置格式4：'[源目录|目的目录]'，比如'[/mnt/pt_music|mnt/emby_music]'，即使用[]括起来代表这个目录不是影视文件，不需要进行识别和重命名，程序会对源目录下所有的文件全部硬链接到目的目录，不会有消息通知等功能
  # 一行的三个目录需要在同一个磁盘分区/共享目录中，有多个目录的，需要映射上级目录，源目录和目的目录为子目录，如果分开映射则可能发生跨盘的问题
  # 未识别的记录同时会在媒体整理->手动识别下面出现，未识别目录只是硬链接一份用于备份，同时手工识别处理后程序也不会主动删除，如果不想要多硬链接一份，可以不配置该目录
  sync_mod: link
  # 【监控目录操作系统类型】：windows、linux。如果是windows，目录同步功能性能会比较差，会导致NAS不能休眠，除非是挂载的windows的远程共享目录或者是windows的docker，否则建议设置为linux
  nas_sys: linux

# 【配置PT站点和检索信息】
pt:
  # 【PT下载使用的客户端软件】：qbittorrent、transmission，需要配置qbittorrent或transmission对应的配置区域
  search_indexer: builtin
  # 【远程搜索自动择优下载开关】：如开启则微信等渠道搜索后会自动择优选择一项下载，如不开启则需要手工点击进入WEB页面选择下载
  # 如没有配置app.domain或无公网环境建议开启，否则无法跳转WEB页面手工选择
  search_auto: true
  # 【远程下载不完整自动订阅】：如开启，远程搜索下载不完整时，会自动添加RSS订阅
  search_no_result_rss: true
  # 【PT站每日签到时间】
  # 两种配置方法，1、配置间隔，单位小时，建议不要设置为24小时的整数倍，避免每天的签到时间一样。2、配置固定时间，如'08:00'，注意要加引号和冒号。3、配置时间范围，如08:00-09:00，表示在该时间范围内随机执行一次
  ptsignin_cron: ''
  # 【PT做种清理开关】：此处配置PT做种时间，做种超过该时间则会自动删种（包括已下载的文件），单位是【天】。
  # 如果是使用COPY模式，这个根据PT下载盘的大小配置，如果是使用LINK模式，这个一般不配置，
  # 不配置或者配置为0则不启用PT做种清理功能
  pt_seeding_time: ''
  # 【RSS订阅开关】：此处配置RSS订阅检查时间间隔，即每隔多长时间检查一下各PT站是否有资源更新，建议不要少于30分钟，单位时间为秒
  # 配置为空或者0则不启用RSS订阅功能
  pt_check_interval: '1800'
  # 【定量搜索RSS开关】：打开后，每隔与置时间会通过PT站资源检索的方式查询和下载订阅，单位：天，不配置则为关
  search_rss_interval: '12'
  # 【下载优先规则】：订阅及远程搜索下载将按此优先规则选择下载资源，字典：site 站点优先、seeder做种数优先
  download_order: seeder

# 【配置Jackett检索器】
  ptrefresh_date_cron: '6'
jackett:
  # 【Jackett ApiKey】：Jackett配置页面右上角复制API Key
  api_key: 4crxxxxx
  # 【Jackett索引器】：Jackett Indexer中添加索引器，选择“Copy Torznab Feed”生成链接填入，可以配置多个，配置上的就会参与检索(注意最后要带/)，配置在前面的优先
  indexers:
  - http://172.16.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/yts/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/mikan/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/1337x/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/acgrip/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/btsow/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/dmhy/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/eztv/results/torznab/
  - http://172.16.0.1:9117/api/v2.0/indexers/ibit/results/torznab/
  host: http://172.16.0.1:9117
  password: ''
prowlarr:
  # 【Prowlarr地址】
  host: http://127.0.0.1:9696
  # 【Prowlarr ApiKey】：Prowlarr设置页面获取API Key
  api_key:
cloudtorrent:
  # 115 Cookie 抓包获取
  cookie:
  # 下载文件保存路径，传递给下载器使用
  save_path:
    movie:
    tv:
    anime:
  # NASTool访问下载文件的映射路径
  save_containerpath:
    movie:
    tv:
    anime:
security:
  # 【媒体服务器webhook允许ip范围】：即只有如下范围的IP才允许调用webhook
  media_server_webhook_allow_ip:
    ipv4: 0.0.0.0/0
    ipv6: ::/0
  # 【Telegram webhook允许ip范围】：即只有如下范围的IP才允许调用webhook
  telegram_webhook_allow_ip:
    ipv4: 0.0.0.0/0
    ipv6: ::/0

# 【实验室】
  api_key: '123456789'
  synology_webhook_allow_ip:
    ipv4: 10.10.10.0/24,172.16.0.0/16
    ipv6: ::/0
  check_apikey: false
laboratory:
  # 【识别增强】关键字猜想
  search_keyword: true
  # 【TMDB缓存过期策略】：是否开启TMDB缓存过期策略，默认7天过期，过期缓存将被删除,  7天内访问过期时间可以被刷新
  tmdb_cache_expire: true
  # 【使用豆瓣名称联想】：开启将使用豆瓣进行电影电视剧的名称联想，否则使用TMDB的数据
  use_douban_titles: false
  # 【精确搜索使用英文名称】：开启后对于精确搜索场景（远程搜索、订阅搜索等）将会使用英文名检索站点资源以提升匹配度，但对有些站点资源标题全是中文的则需要关闭，否则匹配不到
  search_en_title: false
  ignored_words: ''
  replaced_words: ''
  offset_words: ''
  chrome_browser: true
  tmdb_proxy: false
  search_tmdbweb: false
  chatgpt_enable: false
test: false
openai:
  api_key: ''
  api_url: ''
```
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
